// eslint-disable-next-line
export const JOB_ACTIONS = {
  ADD_JOB: 'ADD_JOB',
  VIEW_JOB: 'VIEW_JOB',
  FETCH_JOBS: 'FETCH_JOBS',
  LOAD_JOB_DETAIL: 'LOAD_JOB_DETAIL',
  CLEAR_JOB_DETAIL: 'CLEAR_JOB_DETAIL',
  JOBS_DATA_FETCH_SUCCEEDED: 'JOBS_DATA_FETCH_SUCCEEDED',
  JOBS_DATA_FETCH_FAILED: 'JOBS_DATA_FETCH_FAILED',
  JOB_FETCH_SUCCEEDED: 'JOB_FETCH_SUCCEEDED',
  JOB_FETCH_FAILED: 'JOB_FETCH_FAILED',
  CLEAR_JOB_DETAIL: 'CLEAR_JOB_DETAIL'
};
